### ISSUE TITLE
does not download entire media

### ISSUE THREAD

**Issue by alfratrople** [Avnsx/fansly#1]
ive tried running this several times and it downloads maybe 1/6th of the total images and videos before closing/crashing (??) i dont have the knowledge necessary to offer anything more helpful than that to diagnose the problem, sorry.

**Comment by alfratrople** [comment]
Creating download directories ...
 Starting media download ...
 Downloading media from page: 301510328808644608
[Errno 22] Invalid argument: 'XXXXXXXXX_fansly/Pictures/80_????2.png'

 ERROR: Please copy & paste this on GitHub > Issues & provide a short explanation; closing in 60 seconds.

i think you're right, due to the question marks in the latter half of the filename.

**Comment by Avnsx** [comment]
> Creating download directories ... Starting media download ... Downloading media from page: [Errno 22] Invalid argument: 'XXXXXXXXX_fansly/Pictures/80_????2.png'
> 
> ERROR: Please copy & paste this on GitHub > Issues & provide a short explanation; closing in 60 seconds.
> 
> i think you're right, due to the question marks in the latter half of the filename.

I've wrote code that would actually bypass this bug, but I can't practically test it because I have not found any creator that had pictures with any unallowed characters in their name. If I would update the github source code, with my new update would you be able to launch it through python (to see if i was able to fix it for your creator) or are you using the executable version? Because it's much harder to get a executable version released, due to having to get it whitelisted with various security vendors. Else you'll need to name the creator you're encountering this bug with, so I can see if my update fixed it or not.
