### ISSUE TITLE
Flagged for Malware - updater.exe

### ISSUE THREAD

**Issue by jimcrapo** [Avnsx/fansly#13]
updater.exe was flagged as "Win.Malware.Tedy-9938547-0" by ClamAV on my nas. 

I've deleted it for now, just wanted to give others a head's up. Not sure if its a false positive.

**Comment by jorensc** [comment]
It is...

**Comment by Avnsx** [comment]
> updater.exe was flagged as "Win.Malware.Tedy-9938547-0" by ClamAV on my nas.

I'm aware of it being detected as Virus on ClamAv and do count that antivirus as one of the 💩 ones.
Simply reasoning, because they're an unorganised company, that does not fix or even bother responding / reacting to false positives. Here you can try to get a false positive re-analysed yourself by ClamAv: http://www.clamav.net/reports/fp
(They're not gonna do anything, I tried multiple times a week ago)

You can count Zillya, Antiy-AVL, Yandex & Alibaba to the list of 🚮

Initially my files are always getting detected by above 10 Security Vendors, simply due to the fact they're compiled pyinstaller binaries; which AV's generally don't like. Within a couple days I always get to de-flag around 80% of the false positives and the rest are the above named vendors. 

> Not sure if its a false positive.

You should thank me that I'm taking my time to develop, maintain and publish this software for free, instead of trying to make others think it's malware 🤢

**Comment by Avnsx** [comment]
@jimcrapo  Here check this out bud https://github.com/Cisco-Talos/clamav/issues/465
