### ISSUE TITLE
Not downloading anything?

### ISSUE THREAD

**Issue by KongGal** [Avnsx/fansly#15]
i am subbed to a few on fansly + have some with follower content.
i tried setting up the config my self and with the automatic configurator and both with the same results

Done! Downloaded 0 pictures & 0 videos (0 duplicates declined)

I'm not quite sure what it could be

**Comment by Avnsx** [comment]
did you put anyones name into the config.ini file here for replaceme: 
https://github.com/Avnsx/fansly/blob/e49a3efc3cb2d7d7df6547a487fb8dbf3dad22ee/config.ini#L2 ?

and also did you use the account configuration stuff for authorization and user-agent from your main account? or did you possibly set up an alt account and tried to scrape a fansly creator which you did not subscribe / follow? (since it could be that the creator did not publish any media for the free audience, which would obviously result in the scraper not being able to scrape anything, when you set up the authorisation token from the free account you set up to scrape with fansly scraper)

did you try to scrape other creators too? if yes did that work?

even though this is unlikely; it might be that some creator profiles cause unknown bugs in the scraping algorithm, so than you would need to name me the creator which scraping doesn't work on

**Comment by KongGal** [comment]
nvm me.. too tired
Had added my own username

**Comment by Avnsx** [comment]
> Was it an idea to add it into the script so you start it and it ask for targeted username then?

No, I've decided that the configuration file is the easiest way for all settings.

**Comment by KongGal** [comment]
Ah okay, i know the onlyfans dl script there is, you just open it and it fetches the models you are subbed to and ask you which one to download or if you want to download all subbed models at once to each their folder as normal. https://github.com/k0rnh0li0/onlyfans-dl
