### ISSUE TITLE
[feature] add function to fetch many targets

### ISSUE THREAD

**Issue by Aliaksandr3by** [Avnsx/fansly#21]
[feature] add function to fetch many targets

e.g.
[TargetedCreator]
username = [sdfsfsdff, fffffff, sdfsdf]

p.s. function to get  *.jpg ?

**Comment by Avnsx** [comment]
Not a usefull feature in my opinion, will not add. You can just download one by one.

**Comment by Avnsx** [comment]
@Aliaksandr3by Wait with what creator did you encounter the .jpg file extension missing issue?
I just double checked this issue should've not been possible, because I've added .jpg supported already before

https://github.com/Avnsx/fansly/blob/57e90741b1b4a120b85791424bf0386ba5c4d14e/fansly_scraper.py#L221
