### ISSUE TITLE
Incomplete download

### ISSUE THREAD

**Issue by mssm45** [Avnsx/fansly#52]
Hello,

I noticed that the videos and photos older than a specific date (July 14 2022) were not downloaded.

What could be the reason for this?

Is there a way to specify media download for a specific date range?

Thanks and congrats for this wonderful tool.

**Comment by mssm45** [comment]
The creator is:  username = Alina_Rose
It's the only one I tried so far. I am not subcribed to any other.
I am using the executable version = 0.3.5

Also I noticed that at the end the download window just disapears without opening the folder.
open_folder_when_finished = True

**Comment by Avnsx** [comment]
I tried it for myself and had no issues with past that time, on that creator. What operating system are you using? It does not matter if you are paid subscribed to anyone, it can still download previews, try with other creators that you're just following

``just disapears without opening the folder`` most likely some incompability with your operating system

**Comment by mssm45** [comment]
I am running WIN 10 PRO, 21H2.

Previews of another performer work fine beyond July 2022, and the program ends ok by displaying the download folder.

It looks that something is making the program to crash with the other performer.

**Comment by Avnsx** [comment]
> WIN 10 PRO

Most likely the issue is that you're running it on windows 10 professional. The executable was compiled with Windows 10 Home. Meaning during the compilation progress, python at that time combined all the dlls and stuff so that it runs without raw python code on the HOME version. You're lucky that it works more or less on Windows 10 PRO (also counts for every other verison of windows btw).

Now I could also compile it for windows 10 pro and publish that build for you, which will most likely fix your issue, but then again I would have to keep providing you a pro build for every further version of fansly scraper. Which I'm not planning to do.

The easiest solution is to just run the executable through raw python and continue using it like that in the future. It's basically the exact same usage process, except it's not a executable.

You can download python here: https://www.python.org/downloads/
And download the raw fansly scraper source here: https://github.com/Avnsx/fansly/archive/refs/heads/main.zip

Just copy paste your old config file into the newly downloaded fansly scraper folder and if you already have python installed at that point, all you'll have to do is just to click on fansly_scraper and your system will know how to start it just as if you were running it as executable.

**Comment by mssm45** [comment]
I installed Python and the corresponding scraper. Then I rebooted but it crashes when starting.

Then I tried again with the windows exe version, and this time it worked :)
Not sure what fixed the issue.

Thanks for the help

**Comment by Avnsx** [comment]
> Then I rebooted but it crashes when starting.

I forgot to tell you, you need to install the requirements into your python enviroment first: https://github.com/Avnsx/fansly#requirements
