### ISSUE TITLE
Only downloading videos

### ISSUE THREAD

**Issue by root3d1** [Avnsx/fansly#53]
I last used the previous version of this software a few months ago successfully on an account. However i have updated just now and tried it on the same account with and without update recent download enabled and it only downloads the videos. I have also started fresh by removing the old download directory from the folder to see if it downloads everything and it only downloads the videos still.
Thanks

**Comment by Avnsx** [comment]
Not sure how I'm supposed to help with this, as I don't encounter this issue at all and couldn't replicate it.

You most likely do not even need update recent download anymore, the setting is kind of outdated due to [a contributors patches](https://github.com/Avnsx/fansly/pull/36) to fansly scraper.

We could still try to debug this:
1. What's the creator name, is this is about?
2. Are you subscribed to the creator; if yes are you using the same account that you're subscribed with?
3. Did you try using Fansly Scraper with / without a VPN?
5. What OS are you using Fansly scraper on?
6. Did you try to use the raw source through python instead?
7. Are you aware that fansly scraper now seperates media into [Messages & Timeline](https://github.com/Avnsx/fansly/wiki/Explanation-of-provided-programs-&-their-functionality#4-configini) by default?
