### ISSUE TITLE
All video's I download have strange artifacting and slow down

### ISSUE THREAD

**Issue by spacesandwich** [Avnsx/fansly#71]
The images come out fine but the videos are always choppy with strange artifacting

**Comment by Avnsx** [comment]
Use the version on github, it's most likely because of https://github.com/Avnsx/fansly/issues/58

The python version of fansly scraper, contains the fix already, but there's no compiled executable release for that version yet.

Before I will release a compiled executable, I am planning to do alot of changes for the 3.4.6 version, which I am still working on.

Lacking a little motivation at the moment though
