### ISSUE TITLE
Bug with message scraper in 0.4

### ISSUE THREAD

**Issue by BobafettX** [Avnsx/fansly#90]
I'm using 0.4 with python.
I get the following error from the messages scraper and I haven't unlocked the most recent video, which led me to assume that was the issue.
Other creators messages work and timeline works for that creator.
```
Traceback (most recent call last):
  File "G:\fansly-main\Fansly_Downloader.py", line 1085, in <module>
    contained_posts += [parse_media_info(obj)]
                        ^^^^^^^^^^^^^^^^^^^^^
  File "G:\fansly-main\Fansly_Downloader.py", line 718, in parse_media_info
    if all([default_normal_height, highest_variants_resolution_height, default_normal_height > highest_variants_resolution_height]):
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by Avnsx** [comment]
Oops, switch:
```python
if all([default_normal_height, highest_variants_resolution_height, default_normal_height > highest_variants_resolution_height]):
```
to
```python
if all([default_normal_height is not None, highest_variants_resolution_height is not None, default_normal_height > highest_variants_resolution_height]):
```
and let me know if that solves the issue

**Comment by Avnsx** [comment]
Well you could also just add ``or 0`` to https://github.com/Avnsx/Fansly-Downloader-App/blob/4f228acf52390ac2254302ef7aba2c1595d16316/Fansly_Downloader.py#L653
So that it gets set to 0 if None, that's also going to fix it ``default_normal_height = default_details['height'] or 0``
Same counts for every other spot I wrote ['height']

I'm going to publish a fix for this soon that contains those changes regardless

**Comment by Avnsx** [comment]
Should be fixed with commit https://github.com/Avnsx/Fansly-Downloader-App/commit/2736a5417d0a6db75f56064371b305fdaafcd52b
